version: "3.9"
services:
  app:
    build:
      dockerfile: ./docker/service/Dockerfile
      context: .
      target: dev
    volumes:
      - ./codebase:/opt/app/api
    environment:
      API_SERVER_ADDR: ":3000"
    ports:
      - "${APP_PORT}:3000"